# coding: utf-8

"""
    DB Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.conversation_status import ConversationStatus

class TestConversationStatus(unittest.TestCase):
    """ConversationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationStatus(self):
        """Test ConversationStatus"""
        # inst = ConversationStatus()

if __name__ == '__main__':
    unittest.main()
