# coding: utf-8

"""
    DB Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_conversations_get(self) -> None:
        """Test case for conversations_get

        List conversations
        """
        pass

    def test_conversations_id_get(self) -> None:
        """Test case for conversations_id_get

        Get a conversation by ID
        """
        pass

    def test_conversations_id_patch(self) -> None:
        """Test case for conversations_id_patch

        Update a conversation status or metadata
        """
        pass

    def test_conversations_post(self) -> None:
        """Test case for conversations_post

        Create a new conversation
        """
        pass

    def test_messages_conversation_id_get(self) -> None:
        """Test case for messages_conversation_id_get

        Get messages in a conversation
        """
        pass

    def test_messages_post(self) -> None:
        """Test case for messages_post

        Create a new message
        """
        pass

    def test_products_get(self) -> None:
        """Test case for products_get

        Get products by query
        """
        pass


if __name__ == '__main__':
    unittest.main()
