# coding: utf-8

"""
    DB Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from db_service_client.models.update_conversation_request import UpdateConversationRequest

class TestUpdateConversationRequest(unittest.TestCase):
    """UpdateConversationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateConversationRequest:
        """Test UpdateConversationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateConversationRequest`
        """
        model = UpdateConversationRequest()
        if include_optional:
            return UpdateConversationRequest(
                status = 'pending',
                openai_conv_id = ''
            )
        else:
            return UpdateConversationRequest(
        )
        """

    def testUpdateConversationRequest(self):
        """Test UpdateConversationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
