[project]
name = "generation-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "python-dotenv",
    "pydantic",
    "python-dateutil",
    "urllib3",
    "redis",
    "openai",
    "google-generativeai",
    "matplotlib",
    "beautifulsoup4",
    "fpdf2",
    "mistletoe",
    "tf-keras",
    "tensorflow-macos; sys_platform == 'darwin' and platform_machine == 'arm64'",
    "tensorflow-cpu; sys_platform == 'linux'",
    "py_packages"
]

[tool.uv.sources]
py_packages = { path = "../py_packages", editable = true }
