# coding: utf-8

# flake8: noqa
"""
    DB Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from db_service_client.models.conversation import Conversation
from db_service_client.models.conversation_status import ConversationStatus
from db_service_client.models.create_conversation_request import CreateConversationRequest
from db_service_client.models.create_message_request import CreateMessageRequest
from db_service_client.models.message import Message
from db_service_client.models.message_role import MessageRole
from db_service_client.models.product import Product
from db_service_client.models.update_conversation_request import UpdateConversationRequest
from db_service_client.models.user import User

