# coding: utf-8

"""
    Storage Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from storage_service_client.models.upload_file_request import UploadFileRequest

class TestUploadFileRequest(unittest.TestCase):
    """UploadFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadFileRequest:
        """Test UploadFileRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadFileRequest`
        """
        model = UploadFileRequest()
        if include_optional:
            return UploadFileRequest(
                filename = '',
                filetype = '',
                data = bytes(b'blah')
            )
        else:
            return UploadFileRequest(
                filename = '',
                filetype = '',
                data = bytes(b'blah'),
        )
        """

    def testUploadFileRequest(self):
        """Test UploadFileRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
