# coding: utf-8

"""
    Storage Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from storage_service_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_id_get(self) -> None:
        """Test case for id_get

        Get a file by id
        """
        pass

    def test_root_post(self) -> None:
        """Test case for root_post

        Upload file
        """
        pass


if __name__ == '__main__':
    unittest.main()
