[project]
name = "embedding-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "absl-py==2.3.1",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiohttp-retry==2.9.1",
    "aiosignal==1.4.0",
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "attrs==25.3.0",
    "certifi==2025.7.14",
    "cffi==1.17.1",
    "charset-normalizer==3.4.2",
    "click==8.2.1",
    "colorama==0.4.6",
    "distro==1.9.0",
    "dnspython==2.7.0",
    "fastapi[standard]==0.115.12",
    "fastapi-cli==0.0.7",
    "frozenlist==1.7.0",
    "h11==0.16.0",
    "h5py==3.14.0",
    "httpcore==1.0.9",
    "httptools==0.6.4",
    "httpx==0.28.1",
    "idna==3.10",
    "iniconfig==2.1.0",
    "jiter==0.10.0",
    "jsonpatch==1.33",
    "jsonpointer==3.0.0",
    "keras==3.11.3",
    "langchain-core==0.3.74",
    "langchain-openai==0.3.31",
    "langchain-pinecone==0.2.11",
    "langchain-tests==0.3.20",
    "langsmith==0.4.16",
    "markdown-it-py==3.0.0",
    "mdurl==0.1.2",
    "ml-dtypes==0.5.3",
    "multidict==6.6.4",
    "namex==0.1.0",
    "numpy==2.3.2",
    "openai==1.101.0",
    "optree==0.17.0",
    "orjson==3.11.2",
    "packaging==24.2",
    "pika==1.3.2",
    "pinecone==7.3.0",
    "pinecone-plugin-assistant==1.7.0",
    "pinecone-plugin-interface==0.0.7",
    "pluggy==1.6.0",
    "propcache==0.3.2",
    "py-cpuinfo==9.0.0",
    "pycparser==2.22",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pygments==2.19.2",
    "pymongo==4.14.1",
    "pytest==8.4.1",
    "pytest-asyncio==0.26.0",
    "pytest-benchmark==5.1.0",
    "pytest-codspeed==4.0.0",
    "pytest-recording==0.13.4",
    "pytest-socket==0.7.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv>=1.2.2",
    "pyyaml==6.0.2",
    "regex==2025.7.34",
    "requests==2.32.4",
    "requests-toolbelt==1.0.0",
    "rich==14.1.0",
    "rich-toolkit==0.14.8",
    "shellingham==1.5.4",
    "six==1.17.0",
    "sniffio==1.3.1",
    "starlette==0.46.2",
    "syrupy==4.9.1",
    "tenacity==9.1.2",
    "tiktoken==0.11.0",
    "tqdm==4.67.1",
    "typer==0.16.0",
    "typing-extensions==4.14.1",
    "typing-inspection==0.4.1",
    "urllib3==2.5.0",
    "uvicorn==0.35.0",
    "uvloop==0.21.0",
    "watchfiles==1.1.0",
    "websockets==15.0.1",
    "wrapt==1.17.3",
    "yarl==1.20.1",
    "zstandard==0.24.0",
    "google-cloud-pubsub>=2.33.0",
    "auth0-python>=4.13.0",
    "openapi-client>=1.1.7",
    "py_packages"
]
[tool.uv]
environments = ["platform_python_implementation == 'CPython'"]

[tool.uv.sources]
py_packages = { path = "../py_packages", editable = true }
