name: Deploy services

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        service:
          - name: scheduler
            dockerfile: Dockerfile.scheduler
            image: scheduler
          - name: generation-service
            dockerfile: Dockerfile.generation
            image: generation-service
          - name: embedding-service
            dockerfile: Dockerfile.embedding
            image: embedding-service
          - name: chat
            dockerfile: Dockerfile.chat
            image: chat
          - name: scraper
            dockerfile: Dockerfile.scraper
            image: scraper

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          docker build -f ${{ matrix.service.dockerfile }} \
            --platform linux/amd64 \
            -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/marketing-sentiment-analysis/${{ matrix.service.image }}:latest . && \
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/marketing-sentiment-analysis/${{ matrix.service.image }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ matrix.service.name }} \
            --image us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/marketing-sentiment-analysis/${{ matrix.service.image }}:latest \
            --region us-west1 \
            --platform managed \
            --allow-unauthenticated
