# This workflow integrates all services and runs tests to ensure everything works together.

name: integrate all services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_scraping_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Shell into dir
        run: cd scraping-service
      - name: Install dependencies
        run: npm install
