name: Run tests

on:
  push:
  pull_request:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    environment: staging

    strategy:
      matrix:
        service:
          - name: scheduler
          - name: generation-service
          - name: embedding-service
          - name: chat-service
          - name: scraping-service
          - name: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Bun
        run: |
          curl -fsSL https://bun.com/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Move to service directory
        run: cd ${{ matrix.service.name }}

      - name: Run tests
        run: bun test
